### ISSUE TITLE
NameError: name 'content' is not defined

### ISSUE THREAD

**Issue by mkleinecke** [TGenNorth/NASP#17]
Good morning and thank you very much in advance for your help. I have been trying to set up NASP on our cluster but I can not get it to run. 

Please find my full attempt below: 

```
(NASP) mkleinecke@cheetah:~/TEST/NASP$ nasp
Welcome to NASP version 1.2.0.

Where would you like output files to be written [nasp_results]?

Output folder /home/mkleinecke/TEST/NASP/nasp_results already exists!
Files in it may be overwritten!
Should we continue anyway [N]? y

Where is the reference fasta file you would like to use? MSHR0169_08May15.fasta

Do you want to check the reference for duplicated regions
and skip SNPs that fall in those regions [Y]?

What system do you use for job management (PBS/TORQUE, SLURM, SGE/OGE, and 'none' are currently supported) [SLURM]? PBS
  Would you like to specify a queue/partition to use for all jobs (leave blank to use default queue) []?
  What additional arguments do you need to pass to the job management system []?

Do you have fasta files for external genomes you wish to include [Y]? n

Do you have read files you wish to include [Y]?
Where are these files located [/home/mkleinecke/TEST/NASP]?

Would you like to use Trimmomatic to trim your reads first [N]?

This pipeline currently supports four aligners: BWA, Bowtie2, Novoalign, and SNAP.
You can also provide pre-aligned BAM files, and you can choose as many options as you want.

Would you like to run BWA mem [Y]?
Would you like to set advanced BWA-mem settings [N]?

Would you like to run Bowtie2 [Y]? n

Would you like to run Novoalign [N]?

Would you like to run SNAP [N]?

Do you have pre-aligned SAM/BAM files you wish to include [N]?

This pipeline currently supports four SNP callers: GATK, SolSNP, VarScan, and SAMtools, and you can provide VCF files.
You can choose as many options as you want.

Would you like to run GATK [Y]?
Would you like to set advanced GATK settings [N]?

Would you like to run VarScan [N]?

Would you like to run SAMtools(BCFtools) [N]?

Do you have pre-called VCFfiles you wish to include [N]?

This pipeline can do filtering based on coverage.
If you do not want filtering based on coverage, enter 0.
What is your minimum coverage threshold [10]?

This pipeline can do filtering based on the proportion of reads that match the call made by the SNP caller.
If you do not want filtering based on proportion, enter 0.
What is the minimum acceptable proportion [0.9]?
Would you like to set advanced MatrixGenerator settings [N]?

Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the coverage or proportion filter masked with an 'N' [N]?
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/NASP/bin/nasp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/miniconda3/envs/NASP/lib/python3.8/site-packages/nasp/nasp.py", line 611, in main
    dispatcher.begin(configuration)
  File "/usr/local/miniconda3/envs/NASP/lib/python3.8/site-packages/nasp/dispatcher.py", line 949, in begin
    (index_job_id, reference) = _index_reference(configuration)
  File "/usr/local/miniconda3/envs/NASP/lib/python3.8/site-packages/nasp/dispatcher.py", line 265, in _index_reference
    job_id = _submit_job(configuration["job_submitter"], command, job_parms, hold=True)
  File "/usr/local/miniconda3/envs/NASP/lib/python3.8/site-packages/nasp/dispatcher.py", line 118, in _submit_job
    submit_command = _pbs_command(job_params['name'], job_params['work_dir'], job_params['mem_requested'], job_params['num_cpus'], job_params['walltime'], job_params['queue'], job_params['args'], hold, notify, waitfor_id)
NameError: name 'job_params' is not defined

```
I have tried to run it without scheduler (for testing purposes), but I get a similar error namely `NameError: name 'bam_prefix' is not defined
`

Kind regards,
Mariana

**Comment by corburn** [comment]
Hello @mkleinecke,

Thank you for getting in touch and I apologize for the delayed response. This issue should be resolved by updating to the latest release on bioconda.

**Comment by AmayaCLagos** [comment]
Hi, I have the latest version of NASP but I get the same error as above, I don't understand how to fix it.
![image](https://user-images.githubusercontent.com/58594412/192994438-41a7d19f-76ab-43b1-969b-bdd1964c8d94.png)
