### ISSUE TITLE
NameError: name 'bam_prefix' is not defined

### ISSUE THREAD

**Issue by AmayaCLagos** [TGenNorth/NASP#22]
Hi, I'm really struggling with NASP I get the following error:

Traceback (most recent call last):
  File "/opt/miniconda/envs/NASP/bin/nasp", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda/envs/NASP/lib/python3.8/site-packages/nasp/nasp.py", line 611, in main
    dispatcher.begin(configuration)
  File "/opt/miniconda/envs/NASP/lib/python3.8/site-packages/nasp/dispatcher.py", line 983, in begin
    aligner_output = _align_reads(read_tuple, configuration, dependencies, reference)
  File "/opt/miniconda/envs/NASP/lib/python3.8/site-packages/nasp/dispatcher.py", line 803, in _align_reads
    outfile = os.path.join(work_dir, "{bam_prefix}.bam".format(bam_prefix=bam_prefix))
NameError: name 'bam_prefix' is not defined

I have seen this error before here in the issues comments and the answer to that was that this was going to be fix after the next update which was 2 years ago (the comment, not the update) and then the issue was closed but I got the same error and I dont know how to fix it. Please help

**Comment by illumina-ti** [comment]
Hi,

Just adding a comment to say that I am encountering this exact same error and cannot seem to get around it.

Hopefully some solution can be found!
