### ISSUE TITLE
NASP error

### ISSUE THREAD

**Issue by luciahenrici** [TGenNorth/NASP#8]
Hello,
I'm just starting in using NASP pipeline, but launching the program I have this error, and I cannot fix it:
Do you want to create a master_masked matrix that includes all positions with low-quality positions that failed the coverage or proportion filter masked with an 'N' [N]? N
Traceback (most recent call last):
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1078, in _escape_attrib
    if "&" in text:
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giusi/my_env/bin/nasp", line 11, in <module>
    sys.exit(main())
  File "/home/giusi/my_env/lib/python3.5/site-packages/nasp/nasp.py", line 603, in main
    configuration_parser.write_config(configuration)
  File "/home/giusi/my_env/lib/python3.5/site-packages/nasp/configuration_parser.py", line 484, in write_config
    _write_config_node(root, xml_file)
  File "/home/giusi/my_env/lib/python3.5/site-packages/nasp/configuration_parser.py", line 389, in _write_config_node
    dom = minidom.parseString(ElementTree.tostring(root, 'utf-8'))
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1123, in tostring
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 775, in write
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 940, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 940, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1090, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1056, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize b'' (type bytes)
Can someone help me, please? Many thanks!

**Comment by corburn** [comment]
Hello @luciahenrici. Thank you for reporting this error.
